apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - app1
  - app2
  - app3
configMapGenerator:
  - name: app-html
    files:
      - index.html=app-html/index.html
      - index.css=app-html/index.css
      - entrypoint.sh=app-html/entrypoint.sh
    options:
      disableNameSuffixHash: true
