TEAM_LOGIN = "mhoyer"
MASTER_IP = "192.168.56.110"

Vagrant.configure("2") do |config|
  config.vm.box = "debian/bookworm64"

  # --- Server (K3s controller) ---
  config.vm.define "#{TEAM_LOGIN}S", primary: true do |server|
    server.vm.hostname = "#{TEAM_LOGIN}S"
    server.vm.network "private_network", ip: MASTER_IP

    server.vm.provider "virtualbox" do |vb|
      vb.name = "#{TEAM_LOGIN}S"
      vb.memory = "12288"
      vb.cpus = 8
    end

    server.vm.synced_folder "confs", "/home/vagrant/confs"
    server.vm.synced_folder "scripts", "/home/vagrant/scripts"
    server.vm.synced_folder "project", "/home/vagrant/default-project"
    server.vm.provision "shell", path: "scripts/k3d.sh"
    server.vm.provision "shell", path: "scripts/gitlab.sh"
    server.vm.provision "shell", path: "scripts/init-repository.sh"
    server.vm.provision "shell", path: "scripts/argocd.sh"
  end
end
