apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
patches:
  - target: { kind: Deployment, name: __APP_NAME__ }
    patch: |-
      - op: replace
        path: /metadata/name
        value: app1
      - op: replace
        path: /spec/selector/matchLabels/app
        value: app1
      - op: replace
        path: /spec/template/metadata/labels/app
        value: app1
  - target: { kind: Service, name: __APP_NAME__ }
    patch: |-
      - op: replace
        path: /metadata/name
        value: app1
      - op: replace
        path: /spec/selector/app
        value: app1
